title: Meaning of Math
description: Tackling difficult math concepts through intuitive explanations.
theme: just-the-docs

math: mathjax

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

url: https://www.meaningofmath.com

aux_links:
  Website Repository: https://github.com/LinearDigressions/meaning-of-math

theme: just-the-docs

# Test change